# version: "3.9"

services:
  fe:
    image: node:22.9.0
    environment:
      - HOME=/tmp
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./web-platform:/app
    env_file: [.env]
    working_dir: /app
    ports: ['3000:3000']
    command: ['npm', 'run', 'dev', '--', '--port', '3000']
  be:
    build: ./service-platform
    volumes:
      - './service-platform:/app'
    ports: [ '8000:8000' ]
    working_dir: /app
    env_file: [.env]
    entrypoint: poetry run
    command: [ 'fastapi', 'dev', 'main.py', "--host", "0.0.0.0", "--port", "8000" ]
  